### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Leon83858** [beeradmoore/dlss-swapper#139] opened 2023-06-18 19:55 UTC
settings window not opening 

https://github.com/beeradmoore/dlss-swapper/assets/23504996/3745a96a-fcf0-4a58-ac4d-01ade874ec68

**Comment by beeradmoore** [comment] 2023-06-18 21:59
Thanks for the video. I am going to close this issue as it is a duplicate of #119.

**Closed by beeradmoore** 2023-06-18 21:59 UTC
Labels: bug
