### ISSUE TITLE
[BUG]  Double Ups on steam games

### ISSUE THREAD

**Issue by RyptEdge** [beeradmoore/dlss-swapper#45] opened 2021-10-11 06:29 UTC
Double ups on steam games

**Expected behaviour**
DLSS Swapper ver. 0.9.3.0 shows 2 listings of some of my steam games

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/92291812/136742576-b04c1e37-b9d3-4f11-8cbd-095fe1bf64e6.png)

**Comment by beeradmoore** [comment] 2021-10-12 01:49
That is interesting. I was going to say do you have an OST of a game installed or something and it made it look like it was showing up twice. But there are far too many games surely for it to be that.

Are your games installed on multiple hard drives? Had you previously moved games or are all these installed once and not touched since you did the first install?

**Comment by RyptEdge** [comment] 2021-10-12 02:13
Nope, each game is installed once on the drives that I have, I've launched each game at least once so I can set up the graphics, it never happened on previous versions of DLSS Swapper on Win11 until now.

Some more double ups
![Desktop Screenshot 2021 10 12 - 13 06 22 22](https://user-images.githubusercontent.com/92291812/136879070-68258ca8-a3fa-46dc-90c5-8c9dd8faa716.png)
![Desktop Screenshot 2021 10 12 - 13 04 36 76](https://user-images.githubusercontent.com/92291812/136879076-3f32b6ab-f5e7-43a4-91cd-506f9c06f5ef.png)

**Comment by RyptEdge** [comment] 2021-10-12 02:15
SiN Gold hasn't got an official soundtrack if that's what you're referring to.

**Comment by beeradmoore** [comment] 2021-10-12 05:27
So found the issue, maybe...

To detect Steam games we first find where Steam is installed, and then know `{steam_dir}/steamapps` is a place where games will be installed so its (lets say `C:/Steam/`).

We then open up a Steam file `libraryfolders.vdf` which contains info on where your other Steam libraries are (say `E:/Games/Steam`). Now for some reason this used to only list my OTHER Steam libraries. But now it also contains my initial steam library `C:/Steam/`.

So then we search for games in these 3 locations.
- C:/Steam/
- C:/Steam/
- E:/Games/Steam/
Annnnd whops. Now any game in C:/Steam/ will be listed twice. 

Solution should be straight forward, before we scan for games check for duplicate directories in the libraries list. I'll be sure this is added into the next version to be released (no ETA yet)

If this is what I think the problem is then I would take a guess that the games you have doubled up will be installed on the same drive where Steam itself is installed?

**Comment by RyptEdge** [comment] 2021-10-12 05:48
Yep all the double-ups are on the same drive as steam

**Comment by beeradmoore** [comment] 2021-10-12 05:49
Then consider it fixed! If you are interested in the code change its [here](https://github.com/beeradmoore/dlss-swapper/commit/849843909e604d6311e476adc4ba0d5ff54151c8). This won't be deployed until the new download system is rolled out (which is why I committed it on that other branch, I probably shouldn't have).

**Closed** 2021-10-12 05:51 UTC
Labels: bug
