### ISSUE TITLE
[Feature request] Make text over boxart more readable

### ISSUE THREAD

**Issue by Carlmundo** [beeradmoore/dlss-swapper#19] opened 2021-09-03 07:00 UTC
For games which have dark colours at the bottom of their box art, I am not able to read the text.

Examples:
https://i.imgur.com/GCOqvB3.png
https://i.imgur.com/Ld8EZCx.png

Perhaps white would be a better font colour to use?

**Comment by beeradmoore** [comment] 2021-09-03 07:10
This is a duplicate of this [issue](https://github.com/beeradmoore/dlss-swapper/issues/18).

Will fix soon.

I'm curious, are you using light theme, or some custom theme on your computer?

I wasn't able to replicate the labels going light like this. I shall test some more though.

**Comment by Carlmundo** [comment] 2021-09-03 07:21
From what I can tell, I am not using a custom theme. I went into the theme options and set my theme to "Windows", "Windows (light)" and "Windows 10" but all produced the same result (I re-opened the app each time to make sure).

My DPI scaling is set to 150% in case that helps with your testing.

**Comment by beeradmoore** [comment] 2021-09-05 00:22
I was able to replicate this by changing color from Dark to Light in Settings > Personalization -> Colours
I'll include a fix for this in the next build. Until then closing this issue for #18 (just because it was first)

Thanks again for reporting, and for responding, helps diagnose these issues a lot!

**Closed by beeradmoore** 2021-09-05 00:22 UTC
Labels: feature request
