### ISSUE TITLE
[BUG] Can't access settings on 1.0

### ISSUE THREAD

**Issue by GNS7** [beeradmoore/dlss-swapper#119] opened 2023-02-17 17:28 UTC
**Describe the bug**
Can't access settings (V. 1.0)

**To Reproduce**
1. Go to settings

**Expected behavior**
open settings page.

**Screenshots**
![image](https://user-images.githubusercontent.com/61403819/219723597-bf650c23-5a3a-42b3-9b87-6a6feea90fd0.png)

**Additional context**

**Comment by beeradmoore** [comment] 2023-02-17 20:41
Are you using the installer or port table version of DLSS Swapper?

**Comment by MelvinSmiley** [comment] 2023-02-17 21:08
I have the same problem with 1.0, both with portable and installer version. Had this problem also with 0.95, but there I could fix it by starting the program as admin. This workaround no longer works with 1.0 though.

**Comment by beeradmoore** [comment] 2023-02-17 21:31
For the 1.0 installer version it should generate a log in the %TEMP% directory (open explorer and put that as the path to go to). Log files start with dlss_swapper_ and then I think there is a date after that.

Would you be able to make the issue happen again and then grab the latest error log. Fingers crossed it wrote an error log.

**Comment by beeradmoore** [comment] 2023-02-17 21:35
There was another issue reported that I can't find at the moment, stated that you couldn't navigate away from the games page if games were loading. But the first pic shows the games are loaded 🥲

**Comment by MelvinSmiley** [comment] 2023-02-17 22:24
> I had the portable version in C:\Program Files\DLSS Swapper, started Swapper and it wrote this in the log file:
2023-02-17 23:16:58.661 +01:00 [ERR] Storage.cs:189 SaveDLSSRecordsJsonAsync - Access to the path 'C:\Program Files\DLSS Swapper\StoredData\json\dlss_records.json' is denied.
2023-02-17 23:16:58.676 +01:00 [ERR] Storage.cs:138 SaveSettingsJsonAsync - Access to the path 'C:\Program Files\DLSS Swapper\StoredData\json\settings.json' is denied.
2023-02-17 23:17:00.057 +01:00 [ERR] Storage.cs:138 SaveSettingsJsonAsync - Access to the path 'C:\Program Files\DLSS Swapper\StoredData\json\settings.json' is denied.
2023-02-17 23:17:00.090 +01:00 [ERR] Storage.cs:138 SaveSettingsJsonAsync - Access to the path 'C:\Program Files\DLSS Swapper\StoredData\json\settings.json' is denied.

Now I moved it to C:\ to avoid this and I don't get this log entry anymore, just a couple of ubisoft connect error messages. Still can't access settings though, the wheel starts spinning and then nothing happens.

**Comment by beeradmoore** [comment] 2023-02-17 23:29
If the wheel continues to spin it's because it isn't finished loading games which prevents you from navigating away. 

The not loading games can be fixed by disabling some of the game platforms, but you can't disable them because you can't access settings 😂

I'll make a change to game loading to allow navigation while it's still loading.

**Comment by yaron777** [comment] 2023-02-18 10:36
I have the same problem, unfortunately nothing is logged in the notepad file.
All games are loaded before going to settings. It shows that the settings button is selected, but the right part of the view doesn't change (stays on the game/library view)
I did not have this in previous versions and am using the installer version of 1.0, although the last version I used was the one via the Windows store.
![PrtScr capture](https://user-images.githubusercontent.com/84036957/219855713-d556537d-1d09-4c1c-b68a-6c22cc336243.jpg)

**Comment by wenceslaorl** [comment] 2023-02-19 23:13
Same problem here.

**Comment by beeradmoore** [comment] 2023-02-19 23:17
I was looking into this one on the weekend. Tried making settings page throw errors but it didn't seem to replicate this issue. Must be elsewhere. Will continue to investigate. 

Are people experiencing this issue on Win10 or Win11 or do we have a mixture of both?

When the issue happens does clicking the filter button in the top right bring up the filter menu? Does trying to get to library work?

**Comment by wenceslaorl** [comment] 2023-02-20 01:30
> I was looking into this one on the weekend. Tried making settings page throw errors but it didn't seem to replicate this issue. Must be elsewhere. Will continue to investigate.
> 
> Are people experiencing this issue on Win10 or Win11 or do we have a mixture of both?
> 
> When the issue happens does clicking the filter button in the top right bring up the filter menu? Does trying to get to library work?

Windows 10, installer version.

**Comment by lindareicher** [comment] 2023-02-20 06:42
Same issue here.

Win 11, with both, installer and portabel version.

**Comment by beeradmoore** [comment] 2023-02-20 11:36
Another question, trying to find what connects you all so I can replicate the issue here.

For installer version did you install to the default location (C:\Program Files\DLSS Swapper\) or elsewhere?

For portable version are you running from an extracted location where you have full permissions? (Eg extract into Downloads folder, run from there there, move to desktop, move to documents, etc)

**Comment by lindareicher** [comment] 2023-02-20 11:39
"Yes" for both questions.

**Comment by MelvinSmiley** [comment] 2023-02-20 14:42
I'm using Windows 10 and I was able to reproduce this error with default "C:\Program Files\" or changed install location. Whether it's portable or the installer version also didn't matter.

**Comment by Wxgner** [comment] 2023-02-28 13:33
Same here
W11/Default install

**Comment by Endebert** [comment] 2023-03-07 12:18
I have the same issue, however the cause is regarding Ubisoft connect:

```
UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
```

**Comment by beeradmoore** [comment] 2023-03-07 20:21
I don't believe that is the cause, I get these and still am unable to replicate the error in OP.

That line indicates that there was an error loading a game (or the location of the game library), logged it, and moved on. If anything it just means not all of your Ubisoft games are showing.

I will double check to confirm this is correct or not.

**Comment by Endebert** [comment] 2023-03-08 17:19
@beeradmoore Just tried again, the log entries are created on app launch / on games refresh, so you are probably correct.

Here's all the info I can give you:
- Windows 11 22H2 (Build 22621.1265)
- installer version location: C:\Program Files\DLSS Swapper
- Tried the portable version - same issue
- Tried running as admin - same issue
- In my case, the only log entries are the ones mentioning UbisoftConnectLibrary. E.g.:
  ```
  2023-03-08 18:11:22.898 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
  2023-03-08 18:11:22.906 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
  2023-03-08 18:11:22.907 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
  ```
- The wheel only spins for a moment + when I click on it, but nothing happens.

Here's a short video to demonstrate the behaviour:

https://user-images.githubusercontent.com/9431420/223782444-58dd2145-31a1-4495-b9b1-7fa338910ef6.mp4


Let me know if there's anything I else I can do to help.

**Comment by beeradmoore** [comment] 2023-03-08 21:41
Thanks heaps for all that extra info!

What I think I'll do is make a 1.0.1 with command line options to disable all stores and options to disable auto-loading of games (you would manually have to hit the refresh button until a cache is added).

Theory being if it is the stores or it is a particular game that is failing and not erroring we can narrow it down further.

**Comment by Krasto82** [comment] 2023-04-06 13:40
Same issue here. Win 11 both version.

**Comment by Klajan** [comment] 2023-05-10 16:24
I think I found the problem.
The page string that is checked in the `GoToPage` function in `MainWindows.xaml.cs` is localised for the Settings Page

Since settings does not have a defined tag, one should check `args.IsSettingsInvoked` in `MainNavigationView_ItemInvoked`
A crude but simple fix would be to have:
```
if (args.IsSettingsInvoked)
{
    GoToPage("Settings");
} else if (args.InvokedItem is String invokedItem)
{
    GoToPage(invokedItem);
}
```

**Comment by beeradmoore** [comment] 2023-06-18 22:02
Sorry I didn't see that reply @Klajan. I think you might be 100% right. When I can I'll confirm this and release a small update with that fix.

**Comment by beeradmoore** [comment] 2023-07-01 01:15
This has been implemented. I'll close the issue when v1.1 (or more likely v1.0.2) is released.

**Comment by beeradmoore** [comment] 2023-07-01 07:18
v1.0.2 is now release with this fix. Special thanks again to @Klajan for pointing out the underlying issue.

**Closed by beeradmoore** 2023-07-01 07:18 UTC
Labels: bug
