### ISSUE TITLE
[Feature request] Adding games manually

### ISSUE THREAD

**Issue by SkuLexX** [beeradmoore/dlss-swapper#99] opened 2022-12-08 19:14 UTC
**Adding games manually**
adding the option to add a game directory manually.
app can check if directory contains the dll file without deep search. just like some apps give advanced options instead of automatic detection.

**Comment by beeradmoore** [comment] 2022-12-10 04:17
Thanks for the feature request. Going to close this one as it is a duplicate of #8 

If you go over there and hit subscribe on the right hand side you can get notified when an update is made there. 

It currently is planned, but it isn't in the next build to go out. Possibly the one after that though.

**Closed by beeradmoore** 2022-12-10 04:17 UTC
Labels: feature request
