### ISSUE TITLE
[BUG] dlss swapper not detecting games

### ISSUE THREAD

**Issue by cloud8720** [beeradmoore/dlss-swapper#109] opened 2023-01-28 15:16 UTC
After formatting the game drive, I reinstalled the dlss swapper and the game was not detected.
While loading, only the window appears and the game list does not come out, so I deleted it a few times and reinstalled it, but the same symptoms continue to repeat.
Please tell me the solution.

**Comment by beeradmoore** [comment] 2023-01-28 19:59
What version are you using? If not this one can you try the 1.0 pre-release and see if you are still having issues?

https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.0.0

What games are you expecting to see, Steam? Is Steam still installed or was it on the drive that was formatted?

**Comment by cloud8720** [comment] 2023-01-29 05:56
> 어떤 버전을 사용하고 있습니까? 이것이 아니라면 1.0 시험판을 사용해 보고 여전히 문제가 있는지 확인할 수 있습니까?
> 
> https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.0.0
> 
> Steam에서 어떤 게임을 기대하고 계신가요? Steam이 아직 설치되어 있습니까, 아니면 포맷된 드라이브에 있습니까?

1.0 Test version is in use, and the steam game is installed with two forspoken warhammer40k:darktide, neither of which can be detected.
Installed on formatted drive
Use Windows 11 and install the c: drive.
Game is a d: drive.
I've installed both c: or d: dlss swappers, but the same symptoms

**Comment by beeradmoore** [comment] 2023-01-29 08:52
Can you open DLSS Swapper, go to Settings, and confirm Steam is enabled?

Can you then scroll down in settings to logging and there should be a link to your current error log. Are you able to upload it to your next reply so I can see if it is spitting out any errors?

**Comment by cloud8720** [comment] 2023-01-29 13:34
The game list itself is not generated.And the setting doesn't open.
It just keeps loading like a screenshot.
![dlss](https://user-images.githubusercontent.com/123822005/215329670-30098060-7807-481c-a09c-14595a3e132b.jpg)

**Comment by beeradmoore** [comment] 2023-01-29 18:46
If you open up a file explorer window and enter in the file path %TEMP% it should take you to your temporary files. Sorting by file name hopefully there is some logs starting with the letters dlss, if you could find and post the most recent?

**Comment by cloud8720** [comment] 2023-01-29 18:54
Unfortunately, there are folders in File Explorer, but there are no logs in the folder.
The folder itself is empty.

**Comment by cloud8720** [comment] 2023-01-29 18:58
I checked again, but there is no log file.
The log file that starts with dlss does not exist.
Is it a problem that cannot be solved without a log file?

**Comment by beeradmoore** [comment] 2023-01-29 19:14
May not need the log file but it could be helpful. But even if it existed it may not be logging the actual problem.

Only other thing I can think of in the meantime is to try run DLSS Swapper as administrator.

If you haven't tried the portable version you could try that but I don't think it will work.

If that fails you could also try the latest 0.9 version from the releases tab, but that involves installing certificates and other things to get installed. The instructions are linked there I believe.

From my side I already had plans to change things to allow you to navigate away from the games page while it is loading. When that update is done (no ETA) it would mean you can go to settings and disable steam, disable others (GoG etc) and see if they are the ones causing any issues.

Other than that there should be no reason I know of that this is happening. DLSS Swapper can be installed on any drive and Steam + games can be installed on various other drives. So in theory it should be working 🥲

**Comment by cloud8720** [comment] 2023-01-29 19:30
I also installed the latest 0.9 version, but the 0.9 version stops loading.
I think my computer is weird.

**Comment by beeradmoore** [comment] 2023-01-29 20:32
Haunted PC 😂

Is there anything about your computer that may be different from the norm, like maybe your user account is standard and not admin or anything like that?

**Comment by cloud8720** [comment] 2023-01-30 04:14
My account is an administrator's account and I don't think it's different from others.
The Windows format is about two months old

**Comment by Snazzie** [comment] 2023-02-12 16:50
same problem here, infinite spinner

**Comment by Snazzie** [comment] 2023-02-12 16:51
It worked after unticking all platforms and only select steam

**Comment by beeradmoore** [comment] 2023-02-12 22:29
Hey @Snazzie , would you be able to go to settings and see where your logs are and send over one of your logs from when this issue was happening?

**Comment by cloud8720** [comment] 2023-02-13 03:03
@snazzie , Thank you so much! This solved it.
I've been working on it manually.

**Comment by Snazzie** [comment] 2023-02-13 18:00
> Hey @Snazzie , would you be able to go to settings and see where your logs are and send over one of your logs from when this issue was happening?

no file found at location

**Comment by beeradmoore** [comment] 2023-02-13 20:01
Do you mean there was no logs, or is that a message from the log?

**Comment by Snazzie** [comment] 2023-02-16 04:34
No file

**Comment by NOHEATED** [comment] 2023-02-21 14:56
Same issue, i`m using 1.0, it worked on an old version, I`ve used a guide to uninstall everything corectly

**Comment by Aiesnow** [comment] 2023-02-21 18:46
I have the same issue, here is the content of my log file : 
```
2023-02-21 19:40:35.563 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
2023-02-21 19:40:35.563 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
2023-02-21 19:40:35.904 +01:00 [ERR] UbisoftConnectLibrary.cs:204 ListGamesAsync - Error parsing Ubisoft Connect element. (Did not find expected <document end>.)
2023-02-21 19:40:35.904 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
2023-02-21 19:40:35.904 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
2023-02-21 19:40:35.905 +01:00 [ERR] UbisoftConnectLibrary.cs:91 ListGamesAsync - Could not load Ubisoft Connect item.
```

**Comment by mrRadik** [comment] 2023-02-22 09:22
Same issue, i'm using latest version, log dir is empty.

**Comment by 40OIL** [comment] 2023-02-24 08:31
Same issue,  i'm using 1.0 installer and portable.
I don't have any Store, Ubisoft, GoG or Xbox.
How to add separately installed games manually to dlss-swapper?

**Comment by beeradmoore** [comment] 2023-02-24 08:50
@40OIL , thanks for the info.
Re: manually adding games, it isn't added, it is being tracked [here](https://github.com/beeradmoore/dlss-swapper/issues/8).

**Comment by R1fast** [comment] 2023-03-05 15:49
@beeradmoore first time user on Win 11 pro and having this issue.  V1.0 / installer and confirmed installation instructions incl cert were done correctly.  Failing to load any games/libraries... most of my games are in different drives and those on c: are in a custom folder (not program files).  Just wanted to share and see if any workaround have been established, thanks!

**Comment by Craquehead** [comment] 2023-04-26 00:41
Perhaps a similar issue here; Not only do I get the infinite spinner, I get a "Failed to load game libraries" error at startup if steam is enabled. No logfile is generated at this point. This is on a fresh win11 install, version 1.0.1.0 prerelease. Other platforms work if I disable steam.

**Comment by blaqkatom** [comment] 2023-07-09 22:01
Was meeting "Failed to load game libraries" error on v1.0.0 unless I unchecked 'Xbox App enabled'. Now on v1.0.2, the error is gone, but Xbox App games do not show.

**Comment by beeradmoore** [comment] 2023-07-09 22:26
Sorry for the delay, I didn't realise there are replies.

@R1fast , sorry no ETA. It is part of the next major chunk of work though.

@Craquehead , does 1.0.2 work for you with Steam?

@blaqkatom , did you go re-eanble that in settings? Games from the xbox app also need to be installed after the Xbox app got the update to install games to custom directories. The "game install options" looks like this (DLSS Swapper will also detect across multiple drives. 

![248054183-589cc0ce-809a-4248-8e68-8ae24099f8b1](https://github.com/beeradmoore/dlss-swapper/assets/904737/0642952b-dd6c-458c-96ca-2f0705a86ee6)

**Comment by bandrefilipe** [comment] 2023-07-15 21:10
Hi. Just wanna add that the same issue happened to me today (v1.0.2.0) after I "verified the integrity of game files" on Steam.
DLSS Swapper used to list the game before. Now, after verifying integrity, it cannot.

If I remove the "Hide non-DLSS games" filter, it shows the game, but tells me that "DLSS was not detected in Assetto Corsa Competizione."

**Comment by Craquehead** [comment] 2023-07-17 20:12
At least for me, 1.0.3.1 appears to be working correctly with steam now (and xbox, I don't have any dlss titles on ubi/gog)

Thanks!

**Comment by beeradmoore** [comment] 2023-07-17 20:41
@bandrefilipe , I'll go get Assetto Corsa Competizione and see if I can replicate. 

Does it happen to be one of those games that downloads assets when it launches? If not can you confirm DLSS shows up in the game settings window?

**Comment by beeradmoore** [comment] 2023-07-18 21:50
For those having issues with games disappearing on Steam can you try follow these steps and report back.
- Get a fresh copy of DLSS Swapper v1.0.2 portable from the [releases page](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.2.0).
- Extract the zip and launch `DLSS Swapper.exe`
- Go to `Settings`
- Under `Game Libraries` untick every library except the one you are having issues with (eg. Steam)
- Under `Logging` change it to `Verbose`
- Close DLSS Swapper
- Re-open DLSS Swapper and let your `Games` page load
- Hit `Filter` and untick `Hide non-DLSS games`
- Find a game you know has DLSS in it

Q1: Does DLSS Swapper say it has DLSS?

- If that is a no open the game folder (Open Steam, go to library, right mouse click on game in left menu, select Manage > Browse local files)
- Search for dlss (top In the top right of your file explorer window there is a search box)

Q2: Are there any DLSS Files found? We expect to see `nvngx_dlss.dll`, if we don't see that exact file then DLSS Swapper won't say the game has DLSS in this game.

- If that is a no, launch the game and confirm DLSS is an option in the game settings.

Q3: Was DLSS found in the game settings?

- If you confirmed it was in the game settings then go back to DLSS Swapper, open `Settings` 
- Under `Logging` there is a link next to `Your current log file is`
- Click the link which will take you to the temp folder
- Open that log file (it should be selected by default to make it easier to find)

Q4: Is there any info listed here that seems related to Steam?

- If anything in this log seems related to Steam please upload the log into your reply.

Q5: What game were you checking on Steam?

**Comment by bandrefilipe** [comment] 2023-07-20 04:51
> @bandrefilipe , I'll go get Assetto Corsa Competizione and see if I can replicate.
> 
> Does it happen to be one of those games that downloads assets when it launches? If not can you confirm DLSS shows up in the game settings window?

Hi! I don't think it downloads any assets during launch.
But I managed to fix the issue. At `C:\[...]\Steam\steamapps\common\Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64` there was no `nvngx_dlss.dll` file after "Verifying game files integrity". I can't remember exactly what was the name of the file there, but it had a `.dll.dsll` extension.

I simply added the `nvngx_dlss.dll` file there and now DLSS Swapper "sees" the game again.

**Comment by beeradmoore** [comment] 2023-07-20 04:55
When DLSS Swapper copies assets it will rename the original one `nvngx_dlss.dll.dlsss`, when you use the revert option we simply just move that one back. So that's probably what it found.

But if aster that no `nvngx_dlss.dll` was found in that folder it sounds like the game does not have DLSS, or they went and removed it (or they are relying on nVidia drivers to supply it). Does it appear in the game menu as an option?

**Comment by EarlessChimera2** [comment] 2023-12-03 18:35
> What version are you using? If not this one can you try the 1.0 pre-release and see if you are still having issues?
> 
> https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.0.0
> 
> What games are you expecting to see, Steam? Is Steam still installed or was it on the drive that was formatted?

**Comment by EarlessChimera2** [comment] 2023-12-03 18:39
Hi I am having the same issue it is not detecting any games.  I am expecting it to detect MSFS 2020 which is the boxed version installed via disk, I have unchecked each box in the settings and in steam it finds three games but DLSS is NA and then when I uncheck all the boxes and then check each one individually it detects nothing.  It does start off by saying Failed to load game libraries, any suggestions please, Thank you

**Comment by Gitzzz0** [comment] 2023-12-25 17:23
Hi everybody,
only here to help.

I had the same issue and I was downloading it for MSFS 2020 as well. I have the Microsoft Store version and wouldnt detect the game, so I went ahead and checked, if  the XBOX App was installed...which was not the case! I downloaded the App from the MS Store, matched with the settings above, ran DLSS Swapper as administrator and tadaaa...it showed up. Hope I could help!

**Comment by beeradmoore** [comment] 2023-12-25 22:48
Is running as admin required to get it to swap files once it has shown up?

**Comment by Gitzzz0** [comment] 2023-12-28 16:49
I am not sure whether it is, I just did it. But one it has shown up, it shall be working regardless, otherwise your OS will tell you
________________________________
Von: Brad ***@***.***>
Gesendet: Dienstag, 26. Dezember 2023 05:48
An: beeradmoore/dlss-swapper ***@***.***>
Cc: Gitzzz0 ***@***.***>; Comment ***@***.***>
Betreff: Re: [beeradmoore/dlss-swapper] [BUG] dlss swapper not detecting games (Issue #109)


Is running as admin required to get it to swap files once it has shown up?

**Comment by beeradmoore** [comment] 2023-12-28 22:56
Thanks. I hope to get a good guide up on how to fix this, but without being able to replicate it fully it is difficult. I'll refer to this thread in the future though. Closing for now.

Thanks everyone, have a happy and flighty holidays.

**Closed by beeradmoore** 2023-12-28 22:56 UTC
Labels: bug
