### ISSUE TITLE
[BUG] RTSS preventing DLSS Swapper from starting

### ISSUE THREAD

**Issue by KleKwi** [beeradmoore/dlss-swapper#142] opened 2023-07-04 11:58 UTC
**Describe the bug**
can not startup

**To Reproduce**
1. double-click DLSS Swapper.exe

**Expected behavior**
startup, has graphic interface

**Screenshots**

**Additional context**
seems like it startup, then quit, but has no graphic interface and no warning.

crashdump:
[DLSS Swapper.exe.28920.dmp.zip](https://github.com/beeradmoore/dlss-swapper/files/11949099/DLSS.Swapper.exe.28920.dmp.zip)

**Comment by beeradmoore** [comment] 2023-07-04 22:13
Hey @KleKwi,
Is this with the installer version or the portable version? Also could you let me know what version it is you are trying to use. 

I'll look into the dump file soon.

**Comment by beeradmoore** [comment] 2023-07-05 10:58
Just double checked, 'temp' should be in the 'StoredData' folder which is in the root folder, not in the root folder itself.

Any luck with that?

**Comment by beeradmoore** [comment] 2023-07-05 11:07
Thanks for checking.

Just to confirm, v1.0 portable worked fine?

I think the problem is with an underlying framework that I updated. If that is the case I'll downgrade it and release another update. We don't _need_ to be on the latest, it's just nice.

I wish I could replicate the issue here though so I could pin down what version off the framework broke.

Is there anything about your system that may be fairly unique? Running in non-English, using win10 home, using some FPS overlay that maybe is causing it grief, 240hz monitor, or any else that possibly is out of the norm?

**Comment by beeradmoore** [comment] 2023-07-05 20:38
Interesting. I have RTSS, I'll have to dig around with settings and see if I can replicate.

Had you changed any of the hooks from stock?

**Comment by WhyFin** [comment] 2023-07-07 07:13
I have the same issue with the non-portable installer. Setting the "Application detection level" to "None" allows the DLSS Swapper.exe to launch, otherwise it will not.

**Comment by Kooooolah** [comment] 2023-07-08 18:30
LOL, v1.0.3 either protable and installation won't work with RTSS

**Comment by beeradmoore** [comment] 2023-07-08 21:27
I've been trying all sorts of settings but am struggling to replicate it here so I can report it up the chain and find the last stable version of underlying framework causing the problem 😅

**Comment by beeradmoore** [comment] 2023-07-09 01:44
I was going to ask if people were using an AMD or nVidia GPU, but considering this is DLSS Swapper it's very likely its nVidia 😂

I put my display language into simplified Chinese, rebooted and then ran DLSS Swapper while RTSS was running and it started fine. I also have the same RTSS settings and version as you have in the screenshot. 

I may have to just make multiple versions of portable where I step through the different version numbers of the underlying framework and just ask if you can try each one and let me know where it dies and where it works.

**Comment by beeradmoore** [comment] 2023-07-09 02:46
@KleKwi for reference my 3 test machines were:
- Win11 22H2 23466.1001 (insider build)
- Win11 (TBD)
- Win10 (TBD)

I have also created a portable build of DLSS Swapper which goes from 1.0.2.1 through to 1.0.2.7. Each step of these versions contains an update to the framework that I think is responsible (WindowsAppSDK). 1.0.2.1  matches what 1.0.0.0 has and 1.0.2.7 matches what is in 1.0.2.0 has.

When you have time could you remove the RTSS application detection level changes for DLSS Swapper and then try 1.0.2.1 (hopefully it works) and then go through the versions until it stops working. If they all work then I don't know what to do 😅, but if we can confirm what version breaks I can revert to the version before that and release DLSS Swapper 1.0.3 and report the problem version up stream so hopefully Microsoft can fix it.

| DLSS Swapper Version | WindowsAppSDK Version |
|--------------------------|-----------------------------| 
| [1.0.2.1](https://files.beeradmoore.com/dlss-swapper/DLSS-Swapper-1.0.2.1-portable.zip) | 1.2.221209.1 |
| [1.0.2.2](https://files.beeradmoore.com/dlss-swapper/DLSS-Swapper-1.0.2.2-portable.zip) | 1.2.230118.102 |
| [1.0.2.3](https://files.beeradmoore.com/dlss-swapper/DLSS-Swapper-1.0.2.3-portable.zip) | 1.2.230217.4 |
| [1.0.2.4](https://files.beeradmoore.com/dlss-swapper/DLSS-Swapper-1.0.2.4-portable.zip) | 1.2.230313.1 |
| [1.0.2.5](https://files.beeradmoore.com/dlss-swapper/DLSS-Swapper-1.0.2.5-portable.zip) | 1.3.230331000 |
| [1.0.2.6](https://files.beeradmoore.com/dlss-swapper/DLSS-Swapper-1.0.2.6-portable.zip) | 1.3.230502000 |
| [1.0.2.7](https://files.beeradmoore.com/dlss-swapper/DLSS-Swapper-1.0.2.7-portable.zip) | 1.3.230602002 |

**Comment by KleKwi** [comment] 2023-07-09 03:05
@beeradmoore tow machine's driver and RTSS version is the same, I wiil try the versions you provided.

**Comment by KleKwi** [comment] 2023-07-09 03:24
@beeradmoore 
I'm testing on Windows 11 22H2 22621.1702, I lowered my system version, so I can not test on Windows 11 22H2 22631.1972.
Every version you provided is ok, with or without RTSS. This is odd 😅. Other people has this issue could help testing. @WhyFin @Kooooolah 

| DLSS Swapper Version | With RTSS level low| With RTSS level None|
| --- | --- | --- |
| 1.0.2.1 | ok | ok|
| 1.0.2.2 | ok | ok|
| 1.0.2.3 | ok | ok|
|1.0.2.3| ok| ok|
|1.0.2.4| ok| ok|
|1.0.2.5|ok| ok|
|1.0.2.6| ok| ok|
|1.0.2.7|ok| ok|

**Comment by WhyFin** [comment] 2023-07-09 03:53
Windows 11 Pro 22H2 22621.1848

DLSS Swapper Version | Launch with RTSS enabled
-- | --
1.0.2.1 | **pass**
1.0.2.2 | **pass**
1.0.2.3 | **fail**
1.0.2.4 | **fail**
1.0.2.5 | **fail**
1.0.2.6 | **fail**
1.0.2.7 | **fail**

**Comment by beeradmoore** [comment] 2023-07-09 05:00
Hmmm...

Being able to narrow it down to RTSS I can see multiple issues filed about it over in the WindowsAppSDK or related repositories:
- Jul 15, 2018 - [Crash on startup](https://github.com/File-New-Project/EarTrumpet/issues/268)
- May 4, 2022 - [Unable to load PowerToys settings app version 0.58.0](https://github.com/microsoft/PowerToys/issues/18015)
- May 4, 2022 - [Unpackaged C# WinAppSdk 1.0.3 app crashes when RivaTuner Statistics server app running](https://github.com/microsoft/WindowsAppSDK/issues/2468)
- Mar 16, 2022 - [After Windows10 update EarTrumpet won't start D3D9.dll error](https://github.com/File-New-Project/EarTrumpet/issues/1092)
- Oct 11, 2022 - [WinAppSDK application not opening for some users](https://github.com/microsoft/WindowsAppSDK/issues/3037)
- May 1, 2023 - [Stowed 8007007E (0xc000027b) on some systems upon instantiating Microsoft.UI.Xaml.Window](https://github.com/microsoft/microsoft-ui-xaml/issues/8446)

From the above info the last good version of WindowsAppSDK came out Jan 26 2023, the failing version came out in Feb 23 2023. Neither of these align great with the above timeline of people originally reporting issues. It sounds like this has been reported to both MS and RTSS teams. In fact the first things in the RTSS 7.3.4 changelog are

>
> Improved hook engine:
> - Added WinUI3 runtime libraries to injection ignore triggers list
> - Added 64-bit VK Play overlay library to the list of trigger modules for delayed injection engine
> - Now injection ignore triggers list can specify modules, dynamically loaded by hooked application during runtime. This feature can be used to the exclude applications using delayed load of WPF/WinUI3 runtimes (e.g. Microsoft Power Toys)
> 

(for the above, WinUI3 is WindowsAppSDK)

I was hoping there was a specific version that had a specific change that was obviously the problem so we could point to and wait until that is released so we can update again to the latest WindowsAppSDK, but that doesn't appear to be the case. 

I think the best course of action will be to try a pinned topic of "DLSS Swapper won't launch/crashes on launch" with some helpful tips like "Set DLSS Swapper.exe to ignored in RTSS" and other info on how to get log files if they are generated. Pretty much how lively handles it [here](https://github.com/rocksdanister/lively/wiki/Common-Problems#lively-keeps-crashing-on-startperformance-overlay-visible).

**Comment by JXPCrab** [comment] 2023-08-09 19:53
I have same issue with Windows 10 Pro 22H2 19045.3324

DLSS Swapper v 1.0.2.1 - Pass 
DLSS Swapper v 1.0.2.2 - Pass (longer loading time)

Other version - Fail

**Comment by markishome359** [comment] 2023-10-19 00:33
Weird, getting this on my machine as well, so I'm glad I found this thread.

English, USA
Windows 10 Pro 22H2 19045.3570
Windows Feature Experience Pack 1000.19052.1000.0

RTSS 7.3.2 Beta 2

All application detection levels block DLSS Swapper from launching for installer versions 1.0.2.0 and 1.0.3.1.

**Comment by beeradmoore** [comment] 2023-10-19 03:39
Thanks for the bump, reminded me to go and look into a thread I commented on Guru3D forum about RTSS hooking apps it shouldn't. 

Unwinder (developer of RTSS) replied and has added DLSS Swapper to the built in exclusion list. I just checked and can see it myself in RTSS 7.3.5 Beta 5 (it maybe have been in earlier betas but I can't see downloads/release notes for those). 

I should also be able to add something to DLSS Swapper to prevent it getting hooked for those using older versions of RTSS (looking at you @markishome359 😅), leaving that code below to remember what it is, 

```csharp
// extern "C"
// {
// __declspec(dllexport) DWORD RTSSHooksCompatibility = 0x00000000;
// }
```

**Comment by beeradmoore** [comment] 2023-12-24 00:56
Another update to this. Code has been written to ignore DLSS Swapper for all versions of RTSS, however it can't actually be used until WindowsAppSDK supports full native ahead-of-time (NativeAOT) compilation, which requires CsWinRT to also support it first.

So someday it will be ok, today is not that day.

The workaround to this problem is:
- Use [RTSS 7.3.5 beta 5](https://www.guru3d.com/download/rtss-rivatuner-statistics-server-download/) (or higher) 
- Add DLSS Swapper exclusion in RTSS
- Add the exclusion file added in 7.3.5 beta 5 manually into the file `C:\Program Files (x86)\RivaTuner Statistics Server\ProfileTemplates\DLSS Swapper.exe.cfg` with the data
```
[Hooking]
EnableHooking		= 0
```

Closing this issue for now. Thanks everyone for the help getting to this point.

**Closed by beeradmoore** 2023-12-24 00:56 UTC
Labels: bug
